<?php

/**
 * Class ilObjSrVideoInterviewGUI
 * @author            Fabian Schmid <fs@studer-raimann.ch>
 * @ilCtrl_isCalledBy ilObjSrVideoInterviewGUI: ilRepositoryGUI
 * @ilCtrl_isCalledBy ilObjSrVideoInterviewGUI: ilObjPluginDispatchGUI
 * @ilCtrl_isCalledBy ilObjSrVideoInterviewGUI: ilAdministrationGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilPermissionGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilInfoScreenGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilObjectCopyGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilCommonActionDispatcherGUI
 */
class ilObjSrVideoInterviewGUI extends ilObjectPluginGUI
{
    const CMD_INDEX = 'index';
    const CMD_EDIT = 'edit';
    /**
     * @var \ILIAS\UI\Factory
     */
    protected $ui_component;
    /**
     * @var \ILIAS\UI\Renderer
     */
    protected $ui_renderer;
    /**
     * @var \ILIAS\DI\HTTPServices
     */
    protected $http;

    public function __construct($a_ref_id = 0, $a_id_type = self::REPOSITORY_NODE_ID, $a_parent_node_id = 0)
    {
        global $DIC;
        $this->ui_component = $DIC->ui()->factory();
        $this->ui_renderer  = $DIC->ui()->renderer();
        $this->http         = $DIC->http();
        parent::__construct($a_ref_id, $a_id_type, $a_parent_node_id);
    }

    public function getType()
    {
        return 'xvin';
    }

    public function getAfterCreationCmd()
    {
        return self::CMD_INDEX;
    }

    public function getStandardCmd()
    {
        return self::CMD_INDEX;
    }

    public function executeCommand()
    {
        return parent::executeCommand(); // TODO: Change the autogenerated stub
    }

    public function performCommand($cmd)
    {
        switch ($cmd) {
            case self::CMD_INDEX:
                $this->index();
                break;
            case self::CMD_EDIT:
                $this->edit();
                break;
        }
    }

    private function index() : void
    {
        $this->tpl->addJavaScript("./Customizing/global/plugins/Services/Repository/RepositoryObject/SrVideoInterview/node_modules/recordrtc/RecordRTC.js");
        $this->tpl->addJavaScript("./Customizing/global/plugins/Services/Repository/RepositoryObject/SrVideoInterview/js/script.recordRTC.js");
        $this->tpl->addOnLoadCode("il.Plugins.SrVideoInterview.init();");
        $tpl = new ilTemplate("./Customizing/global/plugins/Services/Repository/RepositoryObject/SrVideoInterview/templates/tpl.record_rtc.html", false, false);

        $this->tpl->setContent($tpl->get());
    }

}
