<?php

/**
 * Class ilObjSrVideoInterviewGUI
 * @author            Fabian Schmid <fs@studer-raimann.ch>
 * @ilCtrl_isCalledBy ilObjSrVideoInterviewGUI: ilRepositoryGUI
 * @ilCtrl_isCalledBy ilObjSrVideoInterviewGUI: ilObjPluginDispatchGUI
 * @ilCtrl_isCalledBy ilObjSrVideoInterviewGUI: ilAdministrationGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilPermissionGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilInfoScreenGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilObjectCopyGUI
 * @ilCtrl_Calls      ilObjSrVideoInterviewGUI: ilCommonActionDispatcherGUI
 */
class ilObjSrVideoInterviewGUI extends ilObjectPluginGUI
{
    const CMD_INDEX = 'index';
    const CMD_EDIT = 'edit';

    public function getType()
    {
        return 'xvin';
    }

    public function getAfterCreationCmd()
    {
        return self::CMD_EDIT;
    }

    public function getStandardCmd()
    {
        return self::CMD_INDEX;
    }

    public function executeCommand()
    {
        return parent::executeCommand(); // TODO: Change the autogenerated stub
    }

    public function performCommand($cmd)
    {
        // $cmd = $this->ctrl->getCmd(self::CMD_INDEX);
        switch ($cmd) {
            case self::CMD_INDEX:
                $this->index();
                break;
            case self::CMD_EDIT:
                $this->edit();
                break;
        }
    }

    private function index() : void
    {

    }

}
